# Generated by Django 5.2.13 on 2026-04-21 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("personal_note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean_word", models.CharField(max_length=100)),
                ("translation", models.CharField(max_length=300)),
                ("romanization", models.CharField(blank=True, max_length=200)),
                ("example_sentence", models.TextField(blank=True)),
                (
                    "source_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="words",
                        to="posts.post",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="saved_words",
                        through="words.UserWord",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["korean_word"],
            },
        ),
        migrations.AddField(
            model_name="userword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="words.word"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userword",
            unique_together={("user", "word")},
        ),
    ]
