# Generated by Django 5.2.13 on 2026-04-21 03:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userword",
            name="easiness_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="userword",
            name="interval",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userword",
            name="last_reviewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userword",
            name="next_review",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userword",
            name="repetitions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="userword",
            index=models.Index(
                fields=["user", "next_review"], name="words_userw_user_id_67acd1_idx"
            ),
        ),
    ]
