# Generated by Django 5.2.13 on 2026-04-21 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_tags"),
        ("texts", "0001_initial"),
        ("words", "0002_userword_easiness_factor_userword_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="context_sentence",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="word",
            name="is_phrase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="word",
            name="source_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_words",
                to="texts.text",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="source_type",
            field=models.CharField(
                choices=[("post", "Post"), ("text", "Text"), ("manual", "Manual")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="korean_word",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="word",
            name="romanization",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="word",
            name="source_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_words",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="translation",
            field=models.CharField(max_length=1000),
        ),
    ]
