# Generated by Django 5.2.13 on 2026-04-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0004_backfill_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean_text", models.TextField()),
                ("korean_normalized", models.TextField(db_index=True, unique=True)),
                ("translation_en", models.TextField()),
                ("romanization", models.CharField(blank=True, max_length=500)),
                ("part_of_speech", models.CharField(blank=True, max_length=50)),
                ("example_sentences", models.JSONField(blank=True, default=list)),
                ("formality_notes", models.TextField(blank=True)),
                ("grammar_notes", models.TextField(blank=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("word", "Single word"),
                            ("phrase", "Phrase / sentence"),
                            ("text", "Full text"),
                        ],
                        default="word",
                        max_length=10,
                    ),
                ),
                ("llm_model_used", models.CharField(default="mock", max_length=100)),
                ("usage_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["korean_normalized"],
                        name="words_trans_korean__64f882_idx",
                    ),
                    models.Index(
                        fields=["entry_type"], name="words_trans_entry_t_0c53f4_idx"
                    ),
                ],
            },
        ),
    ]
